name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pip install poetry pylint

      - name: Install dependencies
        run: poetry install

    #   - name: Lint with flake8
    #     run: pylint .

  test:
    name: Test with pytest
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run pytest
        run: |
          poetry run pytest

  format:
    name: Format code with Black and isort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Poetry
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Format code
        run: |
          poetry run black .
          poetry run isort .
